spring:
  datasource:
    name: planc
    url: jdbc:mysql://rm-3nst8g3h627285fw0.mysql.rds.aliyuncs.com:3306/planb_product_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://rm-3nst8g3h627285fw0ho.mysql.rds.aliyuncs.com:3306/planb_product_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: planb_product
    password: r!foe$giLIOYI8&C
    sql-script-encoding: utf-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.cj.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    max-active: 100
    max-idle: 10
    min-idle: 10
    initial-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size : 15
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    serialization: false

server:
  port: 9004
  tomcat:
    uri-encoding: utf-8
netty:
  port: 9005

bplan:
  encrypt:
    #demo
    privatekey: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDRydUB+ZvnCxJZ9eepileHu8XRV7JPmICj7wdQFjQL9m4ZrD8CLvZxP1w/blfQBXuYCapDZPizKck9+WYmekhP6OVo0vOUsFK8OIdayBBOh9jSfAoq9RJqq1iCUi96Pwp9gz+forzK2dYZUeOdCtm3F6V54VrZb8dGjMmoeATuwzUuQU/XuseD/ZyIJEkzdLbL+cI7Wv2Uxad5u0n2m14DPPruYQ1DYVyDt9gA75ZyLhbap/0nAm407rnBjrzFFgP5wSK4TM3agcxkH8B4y9EDbH6Ge57UzI3zpkG9iFmFxAQqeb2NgZV5AzwutGyPfKQi+nnNgl39Xntb5nU3GpBXAgMBAAECggEBAI5WtPG8HC1s86yaDe6YcL8lhhh9ufwLauzPl1SdW/7p2tYMakve9VLtPHfFNEtuDOehVyaW8a8OIP6tosNkoH+nc0/mIWK3J8uRRzUvHPFLdq+JfZSb5zz8uPbjMFdvQnzaemajkhjIKF3Rk+/PltyFbL7/ShbRopGZoJFvrVkZWatG9TmzgFtJgEg4N73KvaoEj6ckkvVxeTiJe5nTpmdPuVIzBaiWF3IvtPgly6wz/TGe3p1Ur4imdqm6ncK9upytY5SIOCtWcRjearfj+U58377FdWvlnuiGrZw88XcicpL39LkVZ/y9U/OBbhhIK9VwhR1JEzM1f0smpagjXxECgYEA/t9AyVqZdfgIIvqw9kucdPCYXNHEvCNRqvm/GRTanfHERnkKquyVkHXuz3QSw6nNPLNy3xjSMjeF5yKWxnrKZgjJL0dO2qThbw0BtJ4767JAVO5WhL2I96enPpqfdmO6b0BB62+HfSXtAcPjvXXg5Y2K1Uw7y1zF/QQkC3SsupsCgYEA0reA1s8/LNKctnE/sYUAkoXH7xSb91kKPuFnj+Qp6+7BOwcbo26quj1Mc8jq2VWduIiG5ydOLaiDgW6FJKyKEDgyXLHyKrBAXc4KgjtQUVqrvakEpER/hsk9pl73OXHPTxVWI9cmqUFzYDbaq1YjXE949F6+K5JZLEC4LBJ+jvUCgYEAj2P9KAtPwT39HejafIbHjEb8AWSHAa4BOWbu62Z/JFMrsNZSeR1HfBHNfGt6TxiN/jObUga940C3lfUwzJOyoTsaLP46T+ppZjf0GLDZV15esSmyBVY449Qv1JnbUxkCf6qwK4wAtxkKQW77BtF16M/8JsqP7XbRcOrOeJ94ujcCgYEAoemrMGQzUQfMr0u5+3gNhokRph4Z8igS/VpKL4DMzaO6CtddX2mL+mtbsaRzAOkOtlsB/eBv7BmOYwg/enyx4eCsohmB0Vd5Phsya/uTrc+UI7oZ/Pc9Xp6Hpq1WHmfbOhNVC1kpNek69HVx9THNHgNbF7stOWHM73oTipnzcXkCgYEAyVjBzNVVwHl9UcghGtaDHIxjYLtgf4EiwaJTvtRr4TKHfyFs9ktCfpJ+fq6F79H4AUG6MK7D4vBP4Uw1xhBETvoc/irfI3PHKau9SePPEyv6nYsRKYMTnJocSfE5PiMgqYHCtsc1F7j1cnqA05f1LmuNHH7hiqHaLsUcp/GcTnA=
    #test
    #privatekey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDIm5HMzuOll+zD4O2HGsReN9txNQWEr3riO8YXk9TXbJpMVX/OWERLqTqS+Zpwsh3mVLmaJrbKEqIp5NDE7tcd011Jva5ULWmatbYpaSQrkH+Jao/SL6T8K9D/FGdVOk+Ybct6deFAc95EfgA+reGOVgtEaMVzIEy9xTsgE7cnylWuVhT7HZacHeQVooJi1pNEa+rE94DIIqL9F9VoX3vbveVMsOPOA3bGpRWmoJpVmIhXQhHXzq7zNmdVY2TNzTmarEDHZpSOd1rdkin4TxZ4+YukzSaR76sPyX5eN/u7qenfpCBlSTr1KIuxUOyjkwSgqLHatMtcNrZXmpR79r21AgMBAAECggEAOxVGndGZTp4uR4qpqo8BotZEtVTuaSPdx1/fefY6S7BayXytBbMNelM/QyZsjCCJmdr+Rx5724wdYsVXj4jgppIn+Z36CCTP45b9LbkfxAzs4yYVccxChVrKVTZHMNzZsIU11r19OCRoJDgQDmXb9rX035MUBFJRB9tdDJeB7B+vvlNy1sMeEYJ4iolWqUxsXS8eDcLw7fZ/bohR05P16Xv9uA1x80H8u+2Ln9XADoQ0n5dkaoTF0Vt6s0OK0a3hweTC44+Sdx+aKxYQFskOF1edyT4mD/MwOrLQmzc2egi8bD02BO1CJo1ulM2Adpb0S+OBGO7/ogNa4qCPYtvzAQKBgQDz9hDE2ZhTsPQiG3sPN+h+fvPZpHGdHnmIrwLD9wesaVoMw0wTqfkzF10cK7xXv2BDidIp9BoHd/3Gvdi6Dv29knqjbfrFw4uwed2tc4SQpvX4TikSCq8p27d8NJd24CSPb8XdbORY79UkaaU7S4xyD7NwEbhWRZgisCW76eSVoQKBgQDSgdL4uc4yOcBzJ+LWoXxX3DVdYH1rHiSI+7kgCIQdd2eYtxUM0ob9EwOmb6csONh+5YW1uv/ZqpQ4TzPmcEj0EGIleaTPr3BiH8vJdWriwuXuap2d+8NTyvYjnHWauYZ84Ykwqmr+/UtFgnNcnpC7v+J9fR8KGLp4Tmq2hOxHlQKBgCW7MOzBGqYXACsmROodo3+s8tn+bPP3+qQBLVRRqIYp5RuEOQfxifE089mfigmoN6M6dZ63ei8dh8ptIk/kcaoYNY+BOv/LNpecwYRKEX6t0+0LaZ64uE6pBL/ZAnQIRp9Ikjmk1cxLi5OOI1gAX0Bk3UO/+dqd+OGkjLF7gzcBAoGAF7YT43xaY4Hp0Y7OmEp8TRE62ZfCyMwOZXelNJyA9Si7/JGyx0z3c44uvRKai/qjODf2RbAYnZX/OBCD0hMXxJYL2BjJnbMvP35BYCHftkcpyx8rPd5b9BZKf1xiStlW8r4cy+SGRM6XKe81u1sJBnzosCXl1ydN6bs7fe+fBbkCgYAonhwiMeEvCTSPBCOOB8aB4jXzrIkQi8kepa2NFf1vwCe+Oi7CgZct+Uc2MuD42o8oziedHue3WMZD/9VnVR9czVQneuoplzI9ewIPTm+m2+qdUbGmRQOqRb2k2LgtgsNMaaQLSImbSzrHSi7usNA2sk/xtTHhhvGdjvUcQ4mLGg==
  datacenter:
    #url: http://api-sta-datacenter.risewinter.cn/api/bet_orders
    #cameoUrl: http://api-sta-datacenter.risewinter.cn/api/cameo_orders
    url: http://api-hk-datacenter.risewinter.cn/api/bet_orders
    cameoUrl: http://api-hk-datacenter.risewinter.cn/api/cameo_orders
    #apiKey: 7BCGOAUTzc8YhtZSsBYfToB5NfXDtt71ZhMYf5np
    apiKey: vaqRH8pu2zuhMwm48jqD0YUlUumvIqPnGqbIGb9N
    apiVersion: 1

  msg:
    china:
      url: http://smssh1.253.com/msg
      account: CN1135550
      password: lr2kUZcFN3625d
      open: true #短信开关
    international:
      url: http://intapi.253.com/
      account: CI0314361
      password: rNvL3p2qHYc563
      open: true

logging:
  config: classpath:logback.xml



