spring:
  datasource:
    name: planc
    url: jdbc:mysql://rm-3ns0j7yt1qw20z8qk.mysql.rds.aliyuncs.com:3306/bplan_product_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://rm-3nst8g3h627285fw0yo.mysql.rds.aliyuncs.com:3306/planb_product_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    username: bplan_product
    password: 2qjmNALyG&7a*G3S
    sql-script-encoding: utf-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.cj.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    max-active: 100
    max-idle: 10
    min-idle: 10
    initial-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size : 15
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    serialization: false

server:
  port: 9004
  tomcat:
    uri-encoding: utf-8
netty:
  port: 9005
bplan:
  encrypt:
    #demo
    privatekey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAIT0J1wclxjG9BPElgQvSAskiYQTE/Zi5CcKyTcg1Zlr6KWjhf80gHmj+dIMXf/wFXIpBDclw+lPYGcaViQ5VpnwMp0L0loKtO/O3xhumCdqOFVVtbmXu5L23D+JxtJK4q8TFXNMqU/aIvpqD/jJLP/7WHp+bu/o8zQHrp+ZopNDAgMBAAECgYAuHCMebgf1HuL9jBtfHirFOom61YcB13A7HiGEzg1mZSdNcvYA+WtpRHZa49Eh91jou9LrcVyNqOrNNzQS4hPnUoaqgYuoshvmtTEekzb5b5odGeN77yqrF/jw2wAFLLol+xWPRMH6tICeHoj87p3N95vGj62rr0U2mY4+sUwJyQJBAOVKqXQW7uCZZoS7c/w/JQBnWPxoXvGAbZ9NHBGKl65k44T+rmeR3RMgep0t2qWhoxPigg9su01CrUWabWsIOz0CQQCUcMDZkDXhk9QnmNxL/ZFhlotsrfADihYYhNiSB34xaLa89caAf2bmjd+l4LdBJZrnMYLaQO/nVX/HDxdNVPB/AkEAxYqTfy6a0umWR1hwTqvgJv7izWLmGU46I3p9aidrEpZc5iG9BAHI40eiG3R74SLmqqUExGE65Q9C1Kp9Bi9rSQJANu7HH3xzxCgN4h16oRCUhZXNwQlZgiXO6YH4F4p4U9aZkbIupI0BSp8EPgG8L3q4KYi0EQro/SYx5DucdvzRBwJBALkOBYXNROfrWm4SjLG1ExckLXmQsGgJ/G1Vf4NzIb64W49n+o7vKGdoeklvqAZF2H2c4l3UTHAr+nOdQAwHy0w=
    #test
    #privatekey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDIm5HMzuOll+zD4O2HGsReN9txNQWEr3riO8YXk9TXbJpMVX/OWERLqTqS+Zpwsh3mVLmaJrbKEqIp5NDE7tcd011Jva5ULWmatbYpaSQrkH+Jao/SL6T8K9D/FGdVOk+Ybct6deFAc95EfgA+reGOVgtEaMVzIEy9xTsgE7cnylWuVhT7HZacHeQVooJi1pNEa+rE94DIIqL9F9VoX3vbveVMsOPOA3bGpRWmoJpVmIhXQhHXzq7zNmdVY2TNzTmarEDHZpSOd1rdkin4TxZ4+YukzSaR76sPyX5eN/u7qenfpCBlSTr1KIuxUOyjkwSgqLHatMtcNrZXmpR79r21AgMBAAECggEAOxVGndGZTp4uR4qpqo8BotZEtVTuaSPdx1/fefY6S7BayXytBbMNelM/QyZsjCCJmdr+Rx5724wdYsVXj4jgppIn+Z36CCTP45b9LbkfxAzs4yYVccxChVrKVTZHMNzZsIU11r19OCRoJDgQDmXb9rX035MUBFJRB9tdDJeB7B+vvlNy1sMeEYJ4iolWqUxsXS8eDcLw7fZ/bohR05P16Xv9uA1x80H8u+2Ln9XADoQ0n5dkaoTF0Vt6s0OK0a3hweTC44+Sdx+aKxYQFskOF1edyT4mD/MwOrLQmzc2egi8bD02BO1CJo1ulM2Adpb0S+OBGO7/ogNa4qCPYtvzAQKBgQDz9hDE2ZhTsPQiG3sPN+h+fvPZpHGdHnmIrwLD9wesaVoMw0wTqfkzF10cK7xXv2BDidIp9BoHd/3Gvdi6Dv29knqjbfrFw4uwed2tc4SQpvX4TikSCq8p27d8NJd24CSPb8XdbORY79UkaaU7S4xyD7NwEbhWRZgisCW76eSVoQKBgQDSgdL4uc4yOcBzJ+LWoXxX3DVdYH1rHiSI+7kgCIQdd2eYtxUM0ob9EwOmb6csONh+5YW1uv/ZqpQ4TzPmcEj0EGIleaTPr3BiH8vJdWriwuXuap2d+8NTyvYjnHWauYZ84Ykwqmr+/UtFgnNcnpC7v+J9fR8KGLp4Tmq2hOxHlQKBgCW7MOzBGqYXACsmROodo3+s8tn+bPP3+qQBLVRRqIYp5RuEOQfxifE089mfigmoN6M6dZ63ei8dh8ptIk/kcaoYNY+BOv/LNpecwYRKEX6t0+0LaZ64uE6pBL/ZAnQIRp9Ikjmk1cxLi5OOI1gAX0Bk3UO/+dqd+OGkjLF7gzcBAoGAF7YT43xaY4Hp0Y7OmEp8TRE62ZfCyMwOZXelNJyA9Si7/JGyx0z3c44uvRKai/qjODf2RbAYnZX/OBCD0hMXxJYL2BjJnbMvP35BYCHftkcpyx8rPd5b9BZKf1xiStlW8r4cy+SGRM6XKe81u1sJBnzosCXl1ydN6bs7fe+fBbkCgYAonhwiMeEvCTSPBCOOB8aB4jXzrIkQi8kepa2NFf1vwCe+Oi7CgZct+Uc2MuD42o8oziedHue3WMZD/9VnVR9czVQneuoplzI9ewIPTm+m2+qdUbGmRQOqRb2k2LgtgsNMaaQLSImbSzrHSi7usNA2sk/xtTHhhvGdjvUcQ4mLGg==
  datacenter:
    #url: http://api-sta-datacenter.risewinter.cn/api/bet_orders
    #cameoUrl: http://api-sta-datacenter.risewinter.cn/api/cameo_orders
    url: http://api-hk-datacenter.risewinter.cn/api/bet_orders
    cameoUrl: http://api-hk-datacenter.risewinter.cn/api/cameo_orders
    #apiKey: 7BCGOAUTzc8YhtZSsBYfToB5NfXDtt71ZhMYf5np
    apiKey: JY_CE4dtK7sVTGmMDE75QuvzkKb5R1ye0_vySpxr
    apiVersion: 1

  msg:
    china:
      url: http://smssh1.253.com/msg
      account: CN1135550
      password: lr2kUZcFN3625d
      open: true #短信开关
    international:
      url: http://intapi.253.com/
      account: CI0314361
      password: rNvL3p2qHYc563
      open: true

logging:
  config: classpath:logback.xml



