spring:
  datasource:
    name: planc
    url: jdbc:mysql://rm-3nst8g3h627285fw0ho.mysql.rds.aliyuncs.com:3306/open_api?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: planb_product
    password: r!foe$giLIOYI8&C
    sql-script-encoding: utf-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    max-active: 100
    max-idle: 10
    min-idle: 10
    initial-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #        healthCheckPath: /health
        healthCheckInterval: 15s
        instanceId: ${spring.cloud.consul.discovery.service-name}-${spring.profiles.active}-${spring.cloud.consul.discovery.ip-address}-${random.value}
        ip-address: ${HOST_ADDRESS:localhost}
        service-name: auth
        register: true
        heartbeat: ##配置是否进行health check，以及频率
          enabled: true
          ttlValue: 10
        enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  config-location: classpath:/mybatis/config.xml
logging:
  level:
    root: INFO

