spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    name: planc
    #url: jdbc:mysql://rm-3nst8g3h627285fw0.mysql.rds.aliyuncs.com:3306/planb_product_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://rm-3nst8g3h627285fw0.mysql.rds.aliyuncs.com:3306/planb_release_image?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://rm-3nst8g3h627285fw0ho.mysql.rds.aliyuncs.com:3306/planb_test?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://127.0.0.1:3310/planb_release_image?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://sim-xbet-api-mysql-01.cxrxoletpjqx.ap-southeast-1.rds.amazonaws.com:3306/plan_test?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: admin
    password: sim02uOjfNikKlevfHl
    sql-script-encoding: utf-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.cj.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    max-active: 100
    max-idle: 10
    min-idle: 10
    initial-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size : 15
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: sim-xbet-api-redis.r36okn.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    serialization: false
  cloud:
    consul:
      host: ${CONSUL_ADDRESS:200.0.0.5}
      port: 8500
      discovery:
        #        healthCheckPath: /health
        healthCheckInterval: 15s
        instanceId: ${spring.cloud.consul.discovery.service-name}-${spring.profiles.active}-${spring.cloud.consul.discovery.ip-address}-${random.value}
        ip-address: ${HOST_ADDRESS:localhost}
        service-name: datacenter-service
        register: true
        heartbeat: ##配置是否进行health check，以及频率
          enabled: true
          ttlValue: 10
        enabled: true

server:
  port: 9019
  tomcat:
    uri-encoding: utf-8

bplan:
  encrypt:
    #demo
    privatekey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9cyEG2z6ZvFIPMvQhGOcaJ6dMANZ6E8uGzF5SgBX6E7jJe19y/zAI5MQ77P7CahHA7guuN642B+3L0CJUs6Rx4Y3wAmBvs2TJo9KUVuW9XNOv4XxW8BxRWKivW23OTMPdV6VBXfHaAuch9YZ8kptoPjlqV4ArMOeUEcc32BxUshIUH3O/SSZZlaoP8Ws5bzMEfVf30/ayh0lQHF4Cr54m7Fk0b+HeZ46DzyGxNVRrBPYwU2UWCPnhi0/hMJ9GJVLJuqZqhG2e7qayh70fYjA4AM1UfEUFwFlTDFgxQVrf3u2K2ur7IOkkMrELVEMAshXKIQP9Sh0Oqp24XAkWYwlpAgMBAAECggEAFcjXU2KCoEr3ZKgHSocCjA9jPWobP45nKOj3L6Vq4YbDCOgW4bJWY69qoTlvUgvAXt8AmNfuQGhI/9a/G95MWowFNkQPssh+HnGoFUaoxE2YSfEzywtxNilrvD5XMhHBtAIQDqQu21LaIR2KiWiSVjpRf9jv9Ad7mZsxvUosd9CPdvwlamVkWpCfHdn8VKBXsbSvKhTuG3Hjc1ddEntFBpv99orNEz5i/YFIeh3RD9Gt4ufrUCEMJ7gyvXFKodYEam949agKvtVJlaV+F5ejFU6+iG7KHgSCEm7V2LeM1t3ddYsj0OkAYosd3w8XGiseDEVYCB5bCaCoIzurR5QQAQKBgQDjhUYcWl3Kc6tO6f3d6+fBVg0rusgzolEVWdXRSjMw54r02RMmF6N7xazfIz4/8jA6sNc4XO46uaDcV2tnFmXU5q4LV2hsOyA0b7lSJfngVFrERxtuu2c3LVK6hkooE1eGSHKZR0EvDt57SW/I0fws1oJ2ommgUHpXt6f2CxXY4QKBgQDVKecNQK37shyTLuHQNBiwqSA+wp0l+NcfrIhNVl5HIxUkra4jp/BuMcJlfxOBzPvxsdXqruax0EKww8phY1xboSaUYMyjIGiFdNeH4Uw6y6viN903sJPUuynYHKaRbQxrfecvmEMl2jzTCKdkq6VTOz/VL7iz6UX0V4m64gQZiQKBgQCfSuP3Xd1krO83ZOP0yAGOfuzhvPgGDpKuXCMzULvedX34RzL87HftZEzQPSCMLMhPjxhfwdCZFPXmzt3HYwsQsCESl7PocsztaXtaZHQ591VFLnOqZ1Kwcu8E4Jhyznfs8DQr1JNymvpxXs0A0OO5kMXuwW8qaq39U/woa0J0gQKBgDwiLgQXEv3GKTl8KEfL6osrquUJkbt8j3NoAKuQidgXlYdbV5zHa5QqhWSMjLw5T3nHaUljPcE7txSWpykCFrPiqjeBdzktk07Sv1qdvBt6CWsvx0BGl+2TPyKwMm0kDjTkt6s9kPPEtRPzhQVpRqJMPJ2vcLOQQyPC7h/CUtXBAoGAc1TILpPrS2U7wrvjPm57wMMkWKfKCMCzsJTMdGKM0UGVd99086c7mexQGnkMGmN0HyoNhzjJ3kxwiEA24Ti3iGYvdHFneXVEw7Y+1SM9crjmJ8dmbL3g3+V0w5t7N+QH+trMx8YvWQvz0At44YfQO8xQV6GR76/tSZOG2Z1VpmY=
    #test
    #privatekey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDIm5HMzuOll+zD4O2HGsReN9txNQWEr3riO8YXk9TXbJpMVX/OWERLqTqS+Zpwsh3mVLmaJrbKEqIp5NDE7tcd011Jva5ULWmatbYpaSQrkH+Jao/SL6T8K9D/FGdVOk+Ybct6deFAc95EfgA+reGOVgtEaMVzIEy9xTsgE7cnylWuVhT7HZacHeQVooJi1pNEa+rE94DIIqL9F9VoX3vbveVMsOPOA3bGpRWmoJpVmIhXQhHXzq7zNmdVY2TNzTmarEDHZpSOd1rdkin4TxZ4+YukzSaR76sPyX5eN/u7qenfpCBlSTr1KIuxUOyjkwSgqLHatMtcNrZXmpR79r21AgMBAAECggEAOxVGndGZTp4uR4qpqo8BotZEtVTuaSPdx1/fefY6S7BayXytBbMNelM/QyZsjCCJmdr+Rx5724wdYsVXj4jgppIn+Z36CCTP45b9LbkfxAzs4yYVccxChVrKVTZHMNzZsIU11r19OCRoJDgQDmXb9rX035MUBFJRB9tdDJeB7B+vvlNy1sMeEYJ4iolWqUxsXS8eDcLw7fZ/bohR05P16Xv9uA1x80H8u+2Ln9XADoQ0n5dkaoTF0Vt6s0OK0a3hweTC44+Sdx+aKxYQFskOF1edyT4mD/MwOrLQmzc2egi8bD02BO1CJo1ulM2Adpb0S+OBGO7/ogNa4qCPYtvzAQKBgQDz9hDE2ZhTsPQiG3sPN+h+fvPZpHGdHnmIrwLD9wesaVoMw0wTqfkzF10cK7xXv2BDidIp9BoHd/3Gvdi6Dv29knqjbfrFw4uwed2tc4SQpvX4TikSCq8p27d8NJd24CSPb8XdbORY79UkaaU7S4xyD7NwEbhWRZgisCW76eSVoQKBgQDSgdL4uc4yOcBzJ+LWoXxX3DVdYH1rHiSI+7kgCIQdd2eYtxUM0ob9EwOmb6csONh+5YW1uv/ZqpQ4TzPmcEj0EGIleaTPr3BiH8vJdWriwuXuap2d+8NTyvYjnHWauYZ84Ykwqmr+/UtFgnNcnpC7v+J9fR8KGLp4Tmq2hOxHlQKBgCW7MOzBGqYXACsmROodo3+s8tn+bPP3+qQBLVRRqIYp5RuEOQfxifE089mfigmoN6M6dZ63ei8dh8ptIk/kcaoYNY+BOv/LNpecwYRKEX6t0+0LaZ64uE6pBL/ZAnQIRp9Ikjmk1cxLi5OOI1gAX0Bk3UO/+dqd+OGkjLF7gzcBAoGAF7YT43xaY4Hp0Y7OmEp8TRE62ZfCyMwOZXelNJyA9Si7/JGyx0z3c44uvRKai/qjODf2RbAYnZX/OBCD0hMXxJYL2BjJnbMvP35BYCHftkcpyx8rPd5b9BZKf1xiStlW8r4cy+SGRM6XKe81u1sJBnzosCXl1ydN6bs7fe+fBbkCgYAonhwiMeEvCTSPBCOOB8aB4jXzrIkQi8kepa2NFf1vwCe+Oi7CgZct+Uc2MuD42o8oziedHue3WMZD/9VnVR9czVQneuoplzI9ewIPTm+m2+qdUbGmRQOqRb2k2LgtgsNMaaQLSImbSzrHSi7usNA2sk/xtTHhhvGdjvUcQ4mLGg==
  datacenter:
    #url: http://api-sta-datacenter.risewinter.cn/api/bet_orders
    #cameoUrl: http://api-sta-datacenter.risewinter.cn/api/cameo_orders
    url: http://api-sta-datacenter.risewinter.cn/api/bet_orders
    cameoUrl: http://api-sta-datacenter.risewinter.cn/api/cameo_orders
    #apiKey: 7BCGOAUTzc8YhtZSsBYfToB5NfXDtt71ZhMYf5np
    apiKey: 7BCGOAUTzc8YhtZSsBYfToB5NfXDtt71ZhMYf5np
    apiVersion: 1

  msg:
    china:
      url: http://smssh1.253.com/msg
      account: CN1135550
      password: lr2kUZcFN3625d
      open: false #短信开关
    international:
      url: http://intapi.253.com/
      account: CI0314361
      password: rNvL3p2qHYc563
      open: false

#logging:
#  config: classpath:logback.xml



s3:
  accessKey: AKIAZA7GBLE65ELDZI76
  secretKey: 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
  bucketName: dev-xbet-hk

