netty:
  port: 9003

spring:
  rabbitmq:
    host: host.xbet
    username: guest
    password: guest
    port: 5672
    virtual-host: xbet
    publisher-confirms: true
server:
  port: 9100
rabbitmq:
  queue: xbet.queue.name1
