netty:
  port: 9005

spring:
  rabbitmq:
    host: 10.6.0.21
    username: xbet
    password: tlHoXxCgNSitKnGD
    port: 5672
    virtual-host: prod_xbet
    publisher-confirms: true
    #addresses: 10.6.0.21:5672 #,10.6.0.22:5672,10.6.0.23:5672
server:
  port: 9101
rabbitmq:
  queue: xbet.queue.name2
