spring:
  datasource:
    name: planc
    #url: jdbc:mysql://rm-3nst8g3h627285fw0.mysql.rds.aliyuncs.com:3306/planb_product_db?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://sim-xbet-api-mysql-01.cxrxoletpjqx.ap-southeast-1.rds.amazonaws.com:3306/open_api?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: admin
    password: sim02uOjfNikKlevfHl
    sql-script-encoding: utf-8
    platform: mysql
    continue-on-error: false
    separator: //
    driver-class-name: com.mysql.cj.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    max-active: 100
    max-idle: 10
    min-idle: 10
    initial-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size : 15
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: sim-xbet-api-redis.r36okn.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    consul:
      host: ${CONSUL_ADDRESS:200.0.0.5}
      port: ${CONSUL_PORT:8500}
      discovery:
        port: ${SERVER_PORT:${server.port}}
        #        healthCheckPath: /health
        healthCheckInterval: 15s
        instanceId: ${spring.cloud.consul.discovery.service-name}-${spring.profiles.active}-${spring.cloud.consul.discovery.ip-address}-${random.value}
        ip-address: ${HOST_ADDRESS:localhost}
        service-name: api-gateway-server
    gateway:
      loadbalancer:
        use404: true
server:
  port: 8080
logging:
  config: classpath:logback.xml
