// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberListSerbice.proto

package com.splan.xbet.grpclib.lib;

public interface MemberListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.splan.xbet.grpclib.lib.MemberListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   */
  int getPage();

  /**
   * <code>int32 per_page = 2;</code>
   */
  int getPerPage();
}
