// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberListSerbice.proto

package com.splan.xbet.grpclib.lib;

public interface MemberListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.splan.xbet.grpclib.lib.MemberListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  java.util.List<com.splan.xbet.grpclib.lib.Member> 
      getMemberList();
  /**
   * <code>repeated .com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  com.splan.xbet.grpclib.lib.Member getMember(int index);
  /**
   * <code>repeated .com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  int getMemberCount();
  /**
   * <code>repeated .com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  java.util.List<? extends com.splan.xbet.grpclib.lib.MemberOrBuilder> 
      getMemberOrBuilderList();
  /**
   * <code>repeated .com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  com.splan.xbet.grpclib.lib.MemberOrBuilder getMemberOrBuilder(
      int index);
}
