// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Member.proto

package com.splan.xbet.grpclib.lib;

public interface MemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.splan.xbet.grpclib.lib.Member)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string info = 3;</code>
   */
  java.lang.String getInfo();
  /**
   * <code>string info = 3;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();
}
