// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Member.proto

package com.splan.xbet.grpclib.lib;

public final class MemberOuterClass {
  private MemberOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_splan_xbet_grpclib_lib_Member_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_splan_xbet_grpclib_lib_Member_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Member.proto\022\032com.splan.xbet.grpclib.l" +
      "ib\":\n\006Member\022\020\n\010username\030\001 \001(\t\022\020\n\010passwo" +
      "rd\030\002 \001(\t\022\014\n\004info\030\003 \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_splan_xbet_grpclib_lib_Member_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_splan_xbet_grpclib_lib_Member_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_splan_xbet_grpclib_lib_Member_descriptor,
        new java.lang.String[] { "Username", "Password", "Info", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
