// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberLoginSerbice.proto

package com.splan.xbet.grpclib.lib;

public interface MemberLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.splan.xbet.grpclib.lib.MemberLoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
