// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberLoginSerbice.proto

package com.splan.xbet.grpclib.lib;

public interface MemberLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.splan.xbet.grpclib.lib.MemberLoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  boolean hasMember();
  /**
   * <code>.com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  com.splan.xbet.grpclib.lib.Member getMember();
  /**
   * <code>.com.splan.xbet.grpclib.lib.Member member = 1;</code>
   */
  com.splan.xbet.grpclib.lib.MemberOrBuilder getMemberOrBuilder();
}
