// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberLoginSerbice.proto

package com.splan.xbet.grpclib.lib;

public final class MemberLoginSerbice {
  private MemberLoginSerbice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_splan_xbet_grpclib_lib_MemberLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_splan_xbet_grpclib_lib_MemberLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_splan_xbet_grpclib_lib_MemberLoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_splan_xbet_grpclib_lib_MemberLoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030MemberLoginSerbice.proto\022\032com.splan.xb" +
      "et.grpclib.lib\032\014Member.proto\"H\n\022MemberLo" +
      "ginRequest\0222\n\006member\030\001 \001(\0132\".com.splan.x" +
      "bet.grpclib.lib.Member\"$\n\023MemberLoginRes" +
      "ponse\022\r\n\005token\030\001 \001(\t2\205\001\n\022MemberLoginServ" +
      "ice\022o\n\014member_login\022..com.splan.xbet.grp" +
      "clib.lib.MemberLoginRequest\032/.com.splan." +
      "xbet.grpclib.lib.MemberLoginResponseB\002P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.splan.xbet.grpclib.lib.MemberOuterClass.getDescriptor(),
        });
    internal_static_com_splan_xbet_grpclib_lib_MemberLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_splan_xbet_grpclib_lib_MemberLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_splan_xbet_grpclib_lib_MemberLoginRequest_descriptor,
        new java.lang.String[] { "Member", });
    internal_static_com_splan_xbet_grpclib_lib_MemberLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_splan_xbet_grpclib_lib_MemberLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_splan_xbet_grpclib_lib_MemberLoginResponse_descriptor,
        new java.lang.String[] { "Token", });
    com.splan.xbet.grpclib.lib.MemberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
