// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberListSerbice.proto

package com.splan.xbet.grpclib.lib;

public final class MemberListSerbice {
  private MemberListSerbice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_splan_xbet_grpclib_lib_MemberListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_splan_xbet_grpclib_lib_MemberListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_splan_xbet_grpclib_lib_MemberListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_splan_xbet_grpclib_lib_MemberListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MemberListSerbice.proto\022\032com.splan.xbe" +
      "t.grpclib.lib\032\014Member.proto\"3\n\021MemberLis" +
      "tRequest\022\014\n\004page\030\001 \001(\005\022\020\n\010per_page\030\002 \001(\005" +
      "\"H\n\022MemberListResponse\0222\n\006member\030\001 \003(\0132\"" +
      ".com.splan.xbet.grpclib.lib.Member2\201\001\n\021M" +
      "emberListService\022l\n\013member_list\022-.com.sp" +
      "lan.xbet.grpclib.lib.MemberListRequest\032." +
      ".com.splan.xbet.grpclib.lib.MemberListRe" +
      "sponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.splan.xbet.grpclib.lib.MemberOuterClass.getDescriptor(),
        });
    internal_static_com_splan_xbet_grpclib_lib_MemberListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_splan_xbet_grpclib_lib_MemberListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_splan_xbet_grpclib_lib_MemberListRequest_descriptor,
        new java.lang.String[] { "Page", "PerPage", });
    internal_static_com_splan_xbet_grpclib_lib_MemberListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_splan_xbet_grpclib_lib_MemberListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_splan_xbet_grpclib_lib_MemberListResponse_descriptor,
        new java.lang.String[] { "Member", });
    com.splan.xbet.grpclib.lib.MemberOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
